services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.9.0
    environment:
      #      - TZ=Asia/Shanghai
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://192.168.120.177:9200
    #      - ELASTICSEARCH_HOSTS='["http://es01:9200","http://es02:9200","http://es03:9200"]'
    #    volumes:
    #      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601