version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123.com
    volumes:
      - ./data:/data/db
      - ./logs:/data/logs
    ports:
      - 27017:27017
    network_mode: bridge