version: "3.9"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: es
    environment:
      - TZ=Asia/Shanghai
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
