version: '3.1'

services:
  minio:
    image: minio/minio:RELEASE.2021-05-18T00-53-28Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio/data:/data
      - ./minio/config:/minio/config/
    ports:
      - 9000:9000
    networks:
      - localnet 
    command: server ./minio/data



# ● 将 /data 数据目录导出来了
# ● 将 /root/.minio/ 配置文件目录导出来了
# ● command：这个命令是一定需要的，后面跟随的是数据目录路径